base/urls.py
from django.urls import path
from base.views import *

app_name = 'base'
urlpatterns = [
    path('', home,name='home'),
]

learn/urls.py
from django.urls import path
from learn.views import *

app_name = 'learn'
urlpatterns = [
    path('<int:subtopic_id>/', learn_subtopic,name='learn_subtopic'),
    path('help/', show_help,name='help'),
    path('chat/<int:subtopic_id>/', chat_with_ai,name='chat_with_ai'),
]

topics/urls.py
from django.urls import path
from topics.views import *

app_name = 'topics'
urlpatterns = [
    path('', all_topics,name='all_topics'),
    path('add/', add_topic,name='add_topic'),
    path('edit/<int:topic_id>', edit_topic,name='edit_topic'),
    path('edit_subtopic/<int:subtopic_id>', edit_subtopic,name='edit_subtopic'),
    path('delete/<int:topic_id>', delete_topic,name='delete'),
    path('delete_subtopic/<int:subtopic_id>', delete_subtopic,name='delete_subtopic'),
    path('add_subtopic/<int:topic_id>', add_subtopic,name='add_subtopic'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('base.urls')),
    path('learn/', include('learn.urls')),
    path('learners/', include('learners.urls')),
    path('topics/', include('topics.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
]

topics/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default="")
    order = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.name
    
    @property
    def has_subtopics(self) -> bool:
        return len(SubTopic.objects.filter(topic=self))!=0

    @property
    def subtopics(self) -> list:
        return SubTopic.objects.filter(topic=self)

class SubTopic(models.Model):
    name = models.CharField(max_length=200)
    order =  models.IntegerField(default=0)
    description = models.TextField(default="")
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return str(self.topic.name + "| " + self.name + "|" + self.description)[:50]

topics/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from base.utils import prepare_context
from django.contrib import messages
from topics.models import *

# Create your views here.
@login_required
def all_topics(request):
    context = prepare_context(request)
    context['all_topics'] = Topic.objects.all().order_by('order','-name')
    for t in context['all_topics']:
        print(t.has_subtopics)
        print(t.subtopics)
    return render(request,'topics/all_topics.html',context)

@login_required
def add_topic(request):
    context = prepare_context(request)
    if not context['is_moderator']:
        messages.info(request,"This url is restricted, please login as moderator")
        return redirect('/learners/profile')
    if request.method == 'POST':
        if 'save-topic' in request.POST:
            topic_name = request.POST.get('topic_name')
            topic_desc = request.POST.get('topic_desc')
            topic = Topic()
            topic.name = topic_name
            topic.description = topic_desc
            topic.save()
            messages.success(request,topic_name + " successfully added.")
            return redirect('/topics/')
    return render(request,'topics/add_topic.html',context)

@login_required
def edit_topic(request,topic_id):
    context = prepare_context(request)
    if not context['is_moderator']:
        messages.info(request,"This url is restricted, please login as moderator")
        return redirect('/learners/profile')
    topic = get_object_or_404(Topic,id=topic_id)
    context['topic'] = topic
    if request.method == 'POST':
        if 'save-topic' in request.POST:
            topic_name = request.POST.get('topic_name')
            topic_desc = request.POST.get('topic_desc')
            topic.name = topic_name
            topic.description = topic_desc
            topic.save()
            messages.success(request,topic_name + " successfully updated.")
            return redirect('/topics/')
    return render(request,'topics/edit_topic.html',context)

@login_required
def delete_topic(request,topic_id):
    context = prepare_context(request)
    if not context['is_moderator']:
        messages.info(request,"This url is restricted, please login as moderator")
        return redirect('/learners/profile')
    topic = get_object_or_404(Topic,id=topic_id)
    context['topic'] = topic
    topic.delete()
    return redirect('/topics/')

@login_required
def add_subtopic(request,topic_id):
    context = prepare_context(request)
    if not context['is_moderator']:
        messages.info(request,"This url is restricted, please login as moderator")
        return redirect('/learners/profile')
    topic = get_object_or_404(Topic,id=topic_id)
    if not topic:
        messages.error(request,"Topic not found!")
        return redirect('/topics/')
    if request.method == 'POST':
        if 'save-subtopic' in request.POST:
            subtopic_name = request.POST.get('subtopic_name')
            subtopic_desc = request.POST.get('subtopic_desc')
            subtopic = SubTopic()
            subtopic.name = subtopic_name
            subtopic.topic = topic
            subtopic.description = subtopic_desc
            subtopic.save()
            messages.success(request,str(subtopic) + " successfully added.")
            return redirect('/topics/')
    return render(request,'topics/add_subtopic.html',context)

@login_required
def edit_subtopic(request,subtopic_id):
    context = prepare_context(request)
    if not context['is_moderator']:
        messages.info(request,"This url is restricted, please login as moderator")
        return redirect('/learners/profile')
    subtopic = get_object_or_404(SubTopic,id=subtopic_id)
    context['subtopic'] = subtopic
    if request.method == 'POST':
        if 'save-subtopic' in request.POST:
            subtopic_name = request.POST.get('subtopic_name')
            subtopic_desc = request.POST.get('subtopic_desc')
            subtopic.name = subtopic_name
            subtopic.description = subtopic_desc
            subtopic.save()
            messages.success(request,str(subtopic) + " successfully updated.")
            return redirect('/topics/')
    return render(request,'topics/edit_subtopic.html',context)

@login_required
def delete_subtopic(request,subtopic_id):
    context = prepare_context(request)
    if not context['is_moderator']:
        messages.info(request,"This url is restricted, please login as moderator")
        return redirect('/learners/profile')
    subtopic = get_object_or_404(SubTopic,id=subtopic_id)
    subtopic.delete()
    return redirect('/topics/')

topics/templates/topics/add_subtopic.html
{% extends 'base/base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
Add Subtopic
{% endblock %}
{% block head %}
<!-- CSS files -->
<!-- <link rel="stylesheet" href="{% static 'base/css/home.css' %}"> -->
{% endblock %}
{% block content %}
<section class="min-h-screen bg-gradient-to-br from-zinc-900 to-indigo-900/30 w-full grid place-items-center">
    <div class="flex flex-col w-full mx-auto text-center container gap-3">
        <h2 class="text-xl font-raleway font-bold">Add Subtopic</h2>
        <form action="" method="post" class="bg-gradient-to-bl from-zinc-800/20 to-slate-100/10 py-4 border-white border-2 shadow-lg shadow-zinc-100/20 px-5 rounded-sm mx-auto flex flex-col gap-4 w-full max-w-lg">
            {%csrf_token%}
            <input type="text" placeholder="Subtopic Name" class="px-3 py-2 rounded text-black bg-zinc-100/80 placeholder-black" name="subtopic_name" required>
            <textarea name="subtopic_desc" id="desc" cols="10" rows="4" class="rounded text-black bg-zinc-100/80 placeholder-black p-3" placeholder="Subtopic Description" required></textarea>
            <input type="submit" value="Save" class="bg-zinc-900 w-fit  mx-auto px-3 py-2 rounded cursor-pointer" name="save-subtopic">
        </form>
    </div>
</section>
<script src="{% static 'base/js/changeTo.js' %}"></script>
<script src="{% static 'base/js/countdown.js' %}"></script>
{% endblock %}

topics/templates/topics/add_topic.html
{% extends 'base/base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
All Topics
{% endblock %}
{% block head %}
<!-- CSS files -->
<!-- <link rel="stylesheet" href="{% static 'base/css/home.css' %}"> -->
{% endblock %}
{% block content %}
<section class="min-h-screen bg-gradient-to-br from-zinc-900 to-indigo-900/30 w-full grid place-items-center">
    <div class="flex flex-col w-full mx-auto text-center container gap-3">
        <h2 class="text-xl font-raleway font-bold">Add Topic</h2>
        <form action="" method="post" class="bg-gradient-to-bl from-zinc-800/20 to-slate-100/10 py-4 border-white border-2 shadow-lg shadow-zinc-100/20 px-5 rounded-sm mx-auto flex flex-col gap-4 w-full max-w-lg">
            {%csrf_token%}
            <input type="text" placeholder="Topic Name" class="px-3 py-2 rounded text-black bg-zinc-100/80 placeholder-black" name="topic_name" required>
            <textarea name="topic_desc" id="desc" cols="10" rows="4" class="rounded text-black bg-zinc-100/80 placeholder-black p-3" placeholder="Topic Description" required></textarea>
            <input type="submit" value="Save" class="bg-zinc-900 w-fit  mx-auto px-3 py-2 rounded cursor-pointer" name="save-topic">
        </form>
    </div>
</section>
<script src="{% static 'base/js/changeTo.js' %}"></script>
<script src="{% static 'base/js/countdown.js' %}"></script>
{% endblock %}

topics/templates/topics/all_topics.html
{% extends 'base/base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
All Topics
{% endblock %}
{% block head %}
<!-- CSS files -->
<!-- <link rel="stylesheet" href="{% static 'base/css/home.css' %}"> -->
{% endblock %}
{% block content %}
<section class="min-h-screen bg-gradient-to-br from-zinc-900 to-indigo-900/30 w-full grid place-items-center">
    <div class="grid place-items-center pt-16 w-full">
        <div class="flex flex-col gap-4 justify-center w-full mx-auto align-middle">
            <div class="text-center flex flex-col gap-2">
                <h2 class="text-xl lg:text-2xl font-raleway font-bold">Topics Available</h2>
                <h3 class="text-sm">Choose the topic you want to learn!</h3>
            </div>
            {% if is_moderator %}
                <div class="mx-auto flex flex-row gap-3 text-sm">
                    <a href="{% url 'topics:add_topic' %}" class="px-3 py-2 bg-zinc-900">Add Topic</a>
                </div>
            {% endif %}
            <!-- Now list all topics and subtopics -->
            {% if not all_topics %}
                <h2>Topics not added</h2>
            {% else %}
            <ul class="flex flex-col gap-4 px-3 py-4 mb-6">
                {% for topic in all_topics %}
                <div class="max-w-screen-lg w-full
                bg-gradient-to-bl from-zinc-800/20 to-slate-100/10 py-4 border-white border-2 shadow-lg shadow-zinc-100/20 px-5 rounded-sm mx-auto">
                    <div class="flex flex-col lg:flex-row justify-between gap-3 mb-3">
                        <div>
                            <h2 class="font-bold font-raleway lg:text-xl">{{topic.name}}</h2>
                        </div>
                        {% if is_moderator %}
                        <div class="my-auto font-medium flex flew-row gap-3">

                        <a href="{% url 'topics:add_subtopic' topic.id %}" class="px-3 py-2 bg-zinc-900 text-sm mx-auto">Add Subtopic</a>

                        <a href="{% url 'topics:edit_topic' topic.id %}" class="px-3 py-2 bg-zinc-900 text-sm mx-auto">Edit Topic</a>

                        <a href="{% url 'topics:delete' topic.id %}" class="px-3 py-2  text-sm mx-auto">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                              </svg>
                              
                        </a>
                        </div>
                    {% endif %}
                    </div>
                    
                    <h3 class="text-sm
                    ">{{topic.description}}</h3>
                    <ul class="mt-3 ml-4 flex flex-col justify-center align-middle gap-3 list-disc">
                        {% if not topic.has_subtopics %}
                            <h2>No Subtopics</h2>
                        {% else %}
                            {% for st in topic.subtopics %}
                            <li class="flex flex-row w-full justify-between gap-2">
                                <a href="{% url 'learn:learn_subtopic' st.id  %}" class="underline-offset-8 underline">
                                    {{st.name}}
                                </a>
                                {% if is_moderator %}
                                <div class="flex flex-row gap-2">
                                    <a href="{% url 'topics:edit_subtopic' st.id %}" class="underline-offset-8 underline">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                          </svg>
                                          
                                          
                                    </a>
                                    <a href="{% url 'topics:delete_subtopic' st.id %}" class="underline-offset-8 underline">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                          </svg>
                                          
                                    </a>
                                </div>
                                {% endif %}
                            </li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </div>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</section>
<script src="{% static 'base/js/changeTo.js' %}"></script>
<script src="{% static 'base/js/countdown.js' %}"></script>
{% endblock %}

topics/templates/topics/edit_subtopic.html
{% extends 'base/base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
Subtopic Subtopic
{% endblock %}
{% block head %}
<!-- CSS files -->
<!-- <link rel="stylesheet" href="{% static 'base/css/home.css' %}"> -->
{% endblock %}
{% block content %}
<section class="min-h-screen bg-gradient-to-br from-zinc-900 to-indigo-900/30 w-full grid place-items-center">
    <div class="flex flex-col w-full mx-auto text-center container gap-3">
        <h2 class="text-xl font-raleway font-bold">Edit Subtopic</h2>
        <form action="" method="post" class="bg-gradient-to-bl from-zinc-800/20 to-slate-100/10 py-4 border-white border-2 shadow-lg shadow-zinc-100/20 px-5 rounded-sm mx-auto flex flex-col gap-4 w-full max-w-lg">
            {%csrf_token%}
            <input type="text"value="{{subtopic.name}}" class="px-3 py-2 rounded text-black bg-zinc-100/80 placeholder-black" name="subtopic_name" required>
            <textarea name="subtopic_desc" id="desc" cols="10" rows="4" class="rounded text-black bg-zinc-100/80 placeholder-black p-3" placeholder="Subtopic Description" required>{{subtopic.description}}</textarea>
            <input type="submit" value="Save" class="bg-zinc-900 w-fit  mx-auto px-3 py-2 rounded cursor-pointer" name="save-subtopic">
        </form>
    </div>
</section>
<script src="{% static 'base/js/changeTo.js' %}"></script>
<script src="{% static 'base/js/countdown.js' %}"></script>
{% endblock %}

topics/templates/topics/edit_topic.html
{% extends 'base/base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
Edit Topic
{% endblock %}
{% block head %}
<!-- CSS files -->
<!-- <link rel="stylesheet" href="{% static 'base/css/home.css' %}"> -->
{% endblock %}
{% block content %}
<section class="min-h-screen bg-gradient-to-br from-zinc-900 to-indigo-900/30 w-full grid place-items-center">
    <div class="flex flex-col w-full mx-auto text-center container gap-3">
        <h2 class="text-xl font-raleway font-bold">Edit Topic: {{topic.name}}</h2>
        <form action="" method="post" class="bg-gradient-to-bl from-zinc-800/20 to-slate-100/10 py-4 border-white border-2 shadow-lg shadow-zinc-100/20 px-5 rounded-sm mx-auto flex flex-col gap-4 w-full max-w-lg">
            {%csrf_token%}
            <input type="text" value="{{topic.name}}" class="px-3 py-2 rounded text-black bg-zinc-100/80 placeholder-black" name="topic_name" required>
            <textarea name="topic_desc" id="desc" cols="10" rows="4" class="rounded text-black bg-zinc-100/80 placeholder-black p-3" required>{{topic.description}}</textarea>
            <input type="submit" value="Save" class="bg-zinc-900 w-fit  mx-auto px-3 py-2 rounded cursor-pointer" name="save-topic">
        </form>
    </div>
</section>
{% endblock %}