base/urls.py
from django.urls import path
from base.views import *

app_name = 'base'
urlpatterns = [
    path('', home,name='home'),
]

learn/urls.py
from django.urls import path
from learn.views import *

app_name = 'learn'
urlpatterns = [
    path('<int:subtopic_id>/', learn_subtopic,name='learn_subtopic'),
    path('help/', show_help,name='help'),
    path('chat/<int:subtopic_id>/', chat_with_ai,name='chat_with_ai'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('base.urls')),
    path('learn/', include('learn.urls')),
    path('learners/', include('learners.urls')),
    path('topics/', include('topics.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
]

learn/models.py
from django.db import models
from learners.models import Learner
from topics.models import SubTopic
from django.utils import timezone

# Create your models here.
class Chat(models.Model):
    message = models.TextField()
    learner = models.ForeignKey(Learner,on_delete=models.CASCADE)
    msg_type = models.CharField(max_length=100,default="")
    from_ai = models.BooleanField(default=True)
    subtopic = models.ForeignKey(SubTopic,on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return "Learner: "+self.learner.user.first_name + " " + self.learner.user.last_name + " From AI " + str(self.from_ai) +" Message Type: "+ self.msg_type + " Message content: "+ str(self.message)[:30] + "..."

class LearningInformation(models.Model):
    chat = models.ForeignKey(Chat,on_delete=models.CASCADE)
    information = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return "Information for chat-id: "+str(self.chat.id) + " Information content: "+str(self.information)[:20]

class Question(models.Model):
    information = models.ForeignKey(LearningInformation,on_delete=models.CASCADE)
    is_available = models.BooleanField(default=True)
    is_answered = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField(default="")
    is_answer_correct = models.BooleanField(default=False)
    answer_response = models.TextField(default="",blank=True,null=True)
    used_on = models.DateTimeField(blank=True,null=True)
    def __str__(self) -> str:
        return "Question for info-id: "+str(self.information.id) +" content: " + str(self.content)[:30] + str(self.used_on)

learn/views.py
from django.shortcuts import render,redirect,get_object_or_404
from base.utils import prepare_context
from topics.models import *
from learn.models import *
from django.views.decorators.http import require_http_methods
from learn.prompts import *
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.decorators import login_required

PASS_PERCENTAGE = 50

# Create your views here.
@login_required
def learn_subtopic(request,subtopic_id):
    context = prepare_context(request)
    subtopic = get_object_or_404(SubTopic,id=subtopic_id)
    # context['todos'] = Todo.objects.all()
    start_history = Chat.objects.filter(subtopic=subtopic,learner=context['learner']).order_by('created_on')
    print("Length: ",len(start_history))
    if len(start_history) == 0:
        # The learner has started learning the topic for the first time!
        # create intro_to_topic_chat message
        createStartingInformationPrompt(subtopic,context)
    context['history'] = Chat.objects.filter(subtopic=subtopic,learner=context['learner']).order_by('created_on')
    context['subtopic'] = subtopic
    print(context)
    return render(request,'learn/learn.html',context)

@require_http_methods(['POST'])
def chat_with_ai(request,subtopic_id):
    context = prepare_context(request)
    subtopic = get_object_or_404(SubTopic,id=subtopic_id)
    context['subtopic'] = subtopic
    chat = None
    prompt_input = str(request.POST.get('prompt'))
    if prompt_input.startswith('/start'):
        current_information = LearningInformation.objects.filter(chat__learner=context['learner'],chat__subtopic=subtopic).order_by('-created_on').first()
        print(current_information)
        createLearnerPrompt(subtopic,context,input=prompt_input)
        available_questions = Question.objects.filter(information = current_information,is_available=True)
        print("available questions:\n",available_questions)
        if len(available_questions) == 0:
            # generate 5 more questions and choose one
            createQuestions(subtopic,context,info=current_information)
            current_question = Question.objects.filter(information = current_information).first()
        else:
            current_question = available_questions.first()
        current_question.is_available = False
        current_question.used_on = timezone.now()
        current_question.save()
        createQuestionPrompt(subtopic,context,question=current_question.content)

    elif prompt_input.startswith('/answer'):
        prompt_reponse = prompt_input[len(str("/answer")):]
        current_information = LearningInformation.objects.filter(chat__learner=context['learner'],chat__subtopic=subtopic).order_by('-created_on').first()
        print(current_information)
        createLearnerPrompt(subtopic,context,input=prompt_input)
        available_questions = Question.objects.filter(information = current_information).order_by('-used_on')
        # print("available questions:\n",available_questions)
        current_question = available_questions.first()
        current_question.is_answered = True
        current_question.answer_response = prompt_reponse
        if is_answer_correct_ques(subtopic,context,current_question):
            current_question.is_answer_correct = True
        else:
            current_question.is_answer_correct = False
        current_question.save()
    elif prompt_input.startswith('/evaluate'):
        # prompt_reponse = prompt_input[len(str("/evaluate")):]
        total_questions_answered = 0
        total_questions_answered_correctly = 0
        informations = LearningInformation.objects.filter(chat__learner=context['learner'],chat__subtopic=subtopic).order_by('-created_on')
        createLearnerPrompt(subtopic,context,input=prompt_input)
        for info in informations:
            answered_questions = Question.objects.filter(information = info,is_answered = True).order_by('-used_on')
            total_questions_answered += len(answered_questions)
            correct_questions = Question.objects.filter(information = info,is_answered = True,is_answer_correct=True).order_by('-used_on')
            total_questions_answered_correctly += len(correct_questions)
        percentage = (total_questions_answered_correctly/total_questions_answered)*100
        if percentage >= PASS_PERCENTAGE:
            # Your have passed
            createHelpPrompt(subtopic,context,message="You have passed this subtopic, with a percentage of "+str(percentage)+". You can continue learning or choose to move to next subtopic")
            all_topics = Topic.objects.all().order_by('order','-name')
            next_subtopic = None
            flag = False
            for topic in all_topics:
                for st in topic.subtopics:
                    if flag:
                        next_subtopic = st
                    flag = st == subtopic
            messages.success(request,"You have passed this subtopic, with a percentage of "+str(percentage)+". You can continue learning or choose to move to next subtopic")
            if next_subtopic == None:
                context['redirect_to'] = '/topics/'
            else:
                context['redirect_to'] = '/learn/'+str(next_subtopic.id)+'/'
        else:
            createHelpPrompt(subtopic,context,message="You have not passed this subtopic, with a percentage of "+str(percentage)+". You need "+str(PASS_PERCENTAGE) + " to pass to next subtopic.")
    context['history'] = Chat.objects.filter(subtopic=subtopic,learner=context['learner']).order_by('created_on')
    print(render(request,'learn/chat.html',context))
    return render(request,'learn/chat.html',context)

def show_help(request):
    context = prepare_context(request)
    return render(request,"learn/help.html",context)

learn/templates/learn/chat.html
{% load static %}
<link rel="stylesheet" href="{% static 'learn/css/chat-scroll.css' %}">
<ul class="flex flex-col w-full px-3 mt-4 gap-3" id="history">
    {% for chat in history %}
    {% load static %}
        {% if chat %}
            {% if chat.from_ai %}
                <li class="flex flex-row justify-between gap-2 chat-prompt">
                    <img src="{% static 'base/images/logo.png' %}" alt="TutorAI" class="w-8 h-8 object-cover rounded-full border border-zinc-50
                        ">
                    <div class="text-sm px-3 py-2 rounded border border-zinc-600 w-full">
                        <article>{{chat.message}}</article>
                        <small>{{chat.created_on}}</small>
                    </div>
                </li>
            {% else %}
                <li class="flex flex-row-reverse justify-between gap-2 chat-prompt">
                        <img src="{{learner.profile_img}}" alt="TutorAI" style="" class="w-8 h-8 object-cover rounded-full border border-zinc-50
                        ">
                    <div class="text-sm px-3 py-2 rounded border border-zinc-600 w-full">
                        <article>{{chat.message}}</article>
                        <small>{{chat.created_on}}</small>
                    </div>
                </li>
            {% endif %}
        {% endif %}
    {% endfor %}
</ul>
{% if redirect_to%}
<div class="hidden">
<div id="redirect_to" data-val="{{redirect_to}}"></div>
</div>
<script>
    var ele = document.getElementById('redirect_to');
    var url = window.location.protocol +"//"+ window.location.hostname +':'+ window.location.port+ele.getAttribute("data-val")
    console.log(url)
    window.location.href = url;
</script>
{% endif %}

learn/templates/learn/help.html
{% extends 'base/base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
All Topics
{% endblock %}
{% block head %}
<!-- CSS files -->
<!-- <link rel="stylesheet" href="{% static 'base/css/home.css' %}"> -->
{% endblock %}
{% block content %}
<section class="min-h-screen bg-gradient-to-br from-zinc-900 to-indigo-900/30 w-full grid place-items-center px-4">
    <div class="flex flex-col w-full mx-auto text-center container gap-3">
        <h2 class="text-xl font-raleway font-bold">Instructions</h2>
        <div class="bg-gradient-to-bl from-zinc-800/20 to-slate-100/10 py-4 border-white border-2 shadow-lg shadow-zinc-100/20 px-5 rounded-sm mx-auto flex flex-col gap-4 w-full max-w-lg container ">
            <ul class="text-left list-decimal ml-3 flex flex-col gap-3 ">
                <li>After choosing the subtopic to learn, you are shown some information about the subtopic. This is information for you to learn, you will be asked questions from this information later.</li>
                <li>When you feel that you are confident with what you learnt, you can use the start prompt to answer some questions regarding the information. Example: "/start learning"</li>
                <li>You can answer the question using /answer prompt. Example: "/answer your answer". After answering a question you will be told whether your answer is correct or not</li>
                <li>If you want to learn more about the subtopic then use the /learn prompt. Example: "/learn more"</li>
                <li>
                    When you feel comfortable with the topic, you can use the evaluate prompt to evaluate your answers till now. Example: "/evaluate everything". If you have done enough questions, you can go to next subtopic.
                </li>
            </ul>
        </div>
    </div>
</section>
<script src="{% static 'base/js/changeTo.js' %}"></script>
<script src="{% static 'base/js/countdown.js' %}"></script>
{% endblock %}

learn/templates/learn/learn.html
{% extends 'base/base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
Learn {{subtopic.name}}
{% endblock %}
{% block head %}
<!-- CSS files -->
<link rel="stylesheet" href="{% static 'learn/css/chat-scroll.css' %}">
{% endblock %}
{% block content %}
<section class="min-h-screen bg-gradient-to-br from-zinc-900 to-indigo-900/30 w-full grid place-items-center">
    <div class="grid place-items-center pt-16 w-full">
        <div class="w-full flex flex-col text-center">
            <div class="my-3 flex flex-row mx-auto gap-4">
                <h1 class="font-bold font-raleway">Learn {{subtopic.name}}</h1>
                <h3 class="text-sm"><a href="{% url 'learn:help' %}" >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
                      </svg>
                      
                </a></h3>
            </div>
        <div class="min-h-[75vh] max-h-[80vh] w-full container mx-auto bg-zinc-800/90 border border-zinc-600 rounded-2xl max-w-[85vw] flex flex-col justify-between gap-2 overflow-hidden">
            <div class="overflow-y-auto h-[75vh] text-left styled-scrollbars" id="history2">

                {% include 'learn/chat.html' %}
            </div>
            <div class="bg-zinc-900 w-full min-h-12 px-4 py-3">
                <form 
                hx-post = "/learn/chat/{{subtopic.id}}/"
                hx-target = "#history2"
                hx-swap = "innerHTML scroll:bottom"
                >
                    <fieldset class="flex flex-row justify-between gap-3 my-auto">
                        <input type="text" class="w-full bg-transparent text-zinc-50 border border-zinc-600 px-3 py-2 rounded" name="prompt" placeholder="Prompt">
                        <img src="{% static 'base/images/loading.gif' %}" alt="loading gif" id="indicator" class="w-8 h-8 my-auto htmx-indicator">
                        <input type="image" src="{% static 'base/images/chat.svg' %}" alt="Submit" class="w-6 h-6 text-white my-auto">
                        <input type="submit" hidden />

                    </fieldset>
                </form>
            </div>
        </div>
        </div>
    </div>
</section>
<script src="https://unpkg.com/htmx.org@1.6.1"></script>
<script>
    document.body.addEventListener('htmx:configRequest',(event) => {
        event.detail.headers['X-CSRFToken'] = "{{csrf_token}}";
    });
    window.onload = function() {
        var elements = document.querySelectorAll(".chat-prompt"); // Replace "myElement" with the ID of the HTML element you want to scroll

        // console.log(elements);
        var lastElement = elements[elements.length - 1];
        // console.log(lastElement);
        lastElement.scrollIntoView();
    }

</script>
{% endblock %}